kind: pipeline
name: Test TS SDK

steps:


- name: Install Packages
  image: node
  commands:
  - cd ./"TS SDK"/
  - npm install --save-dev

- name: Compile Typescript
  image: node
  commands:
  - cd ./"TS SDK"/
  - ./node_modules/.bin/tsc

- name: JS Tests
  image: node
  commands:
  - cd ./"TS SDK"/
  - npm test

- name: Clean Build
  image: node
  commands:
  - cd ./"TS SDK"/
  - ./node_modules/.bin/tsc --build --clean
